version = 1

[approve]
auto_approve_usernames = ["renovate"]

[merge]
method = "rebase_fast_forward"
prioritize_ready_to_merge = true

[merge.automerge_dependencies]
usernames = ["renovate"]
versions = ["minor", "patch"]

[merge.message]
body = "pull_request_body"
body_type = "markdown"
include_pr_number = true
strip_html_comments = true
title = "pull_request_title"

[update]
always = true
ignored_usernames = ["renovate"]
